export const INDIA_CITIES = {
  mumbai: {
    id: 'mumbai',
    name: 'Mumbai',
    body: 'BMC — Brihanmumbai Municipal Corporation',
    shortBody: 'BMC',
    helpline: '1916',
    totalWards: 24,
    mapLabels: ['Bandra West', 'Dadar', 'Colaba', 'Worli', 'Andheri'],
    wards: [
      'Ward H-West (Bandra / Khar)',
      'Ward A (Colaba / Fort)',
      'Ward G-South (Worli / Prabhadevi)',
      'Ward K-West (Andheri West)',
      'Ward D (Malabar Hill)',
      'Ward L (Kurla)',
    ],
    departments: [
      { id: 'PWD', name: 'BMC Public Works Dept (Roads)', head: 'Suresh Patil', phone: '022-22620251' },
      { id: 'SWM', name: 'BMC Solid Waste Management', head: 'Anjali Deshmukh', phone: '022-24935687' },
      { id: 'WATER', name: 'BMC Hydraulic Engineer (Water Supply)', head: 'Vikram Shinde', phone: '022-23631481' },
      { id: 'LIGHT', name: 'BEST & Electrical Cell', head: 'Rajesh Kadam', phone: '022-22874211' },
      { id: 'DISASTER', name: 'BMC Disaster Management Cell', head: 'Mahesh Narvekar', phone: '1916' },
    ],
  },
  bengaluru: {
    id: 'bengaluru',
    name: 'Bengaluru',
    body: 'BBMP — Bruhat Bengaluru Mahanagara Palike',
    shortBody: 'BBMP',
    helpline: '1533',
    totalWards: 198,
    mapLabels: ['Indiranagar', 'Koramangala', 'Whitefield', 'HSR Layout', 'Malleshwaram'],
    wards: [
      'Indiranagar (Ward 80)',
      'Koramangala (Ward 151)',
      'Whitefield (Ward 84)',
      'HSR Layout (Ward 174)',
      'Malleshwaram (Ward 65)',
      'Jayanagar (Ward 153)',
    ],
    departments: [
      { id: 'PWD', name: 'BBMP Major Infrastructure & Roads', head: 'B. S. Prahallad', phone: '080-22221188' },
      { id: 'SWM', name: 'BBMP Solid Waste Management', head: 'Harish Kumar', phone: '080-22110000' },
      { id: 'WATER', name: 'BWSSB (Water Supply & Sewerage)', head: 'V. Ram Prasath', phone: '1916' },
      { id: 'LIGHT', name: 'BESCOM Streetlight Cell', head: 'K. Venkatesh', phone: '1912' },
      { id: 'DISASTER', name: 'BBMP Control Room (1533)', head: 'D. R. Prakash', phone: '1533' },
    ],
  },
  delhi: {
    id: 'delhi',
    name: 'New Delhi',
    body: 'MCD — Municipal Corporation of Delhi',
    shortBody: 'MCD',
    helpline: '1266',
    totalWards: 250,
    mapLabels: ['Connaught Place', 'South Delhi', 'Rohini', 'Karol Bagh', 'Dwarka'],
    wards: [
      'Central Delhi (Zone 1)',
      'South Delhi (Zone 4)',
      'Rohini (Zone 7)',
      'Connaught Place (NDMC)',
      'Karol Bagh (Zone 2)',
      'Dwarka (Zone 9)',
    ],
    departments: [
      { id: 'PWD', name: 'Delhi PWD & MCD Roads Dept', head: 'Rakesh Sharma', phone: '011-23379800' },
      { id: 'SWM', name: 'MCD Sanitation & Conservancy', head: 'Sunil Kumar', phone: '011-23211200' },
      { id: 'WATER', name: 'Delhi Jal Board (DJB Water)', head: 'Anurag Srivastava', phone: '1916' },
      { id: 'LIGHT', name: 'BSES / Tata Power Streetlights', head: 'Praveen Gupta', phone: '19123' },
      { id: 'DISASTER', name: 'Delhi Disaster Control Room', head: 'Sanjiv Kumar', phone: '1077' },
    ],
  },
  pune: {
    id: 'pune',
    name: 'Pune',
    body: 'PMC — Pune Municipal Corporation',
    shortBody: 'PMC',
    helpline: '1800-1030-222',
    totalWards: 41,
    mapLabels: ['Kothrud', 'Viman Nagar', 'Baner', 'Shivajinagar', 'Hadapsar'],
    wards: [
      'Kothrud - Bavdhan',
      'Viman Nagar - Nagar Road',
      'Baner - Balewadi',
      'Shivajinagar - Ghole Road',
      'Hadapsar - Mundhwa',
      'Aundh - Bopodi',
    ],
    departments: [
      { id: 'PWD', name: 'PMC Road Department', head: 'Vikas Dhakane', phone: '020-25501000' },
      { id: 'SWM', name: 'PMC Solid Waste Management', head: 'Asha Raut', phone: '020-25501234' },
      { id: 'WATER', name: 'PMC Water Supply Dept', head: 'Aniruddha Pawaskar', phone: '020-25501100' },
      { id: 'LIGHT', name: 'PMC Electrical Department', head: 'Shrinivas Kandul', phone: '020-25501300' },
      { id: 'DISASTER', name: 'PMC Emergency Cell', head: 'Prashant Ranpise', phone: '020-25501269' },
    ],
  },
  chennai: {
    id: 'chennai',
    name: 'Chennai',
    body: 'GCC — Greater Chennai Corporation',
    shortBody: 'GCC',
    helpline: '1913',
    totalWards: 200,
    mapLabels: ['Adyar', 'Anna Nagar', 'T. Nagar', 'Velachery', 'Mylapore'],
    wards: [
      'Adyar (Zone 13)',
      'Anna Nagar (Zone 8)',
      'T. Nagar (Zone 10)',
      'Velachery (Zone 14)',
      'Mylapore (Zone 9)',
      'Royapettah (Zone 5)',
    ],
    departments: [
      { id: 'PWD', name: 'GCC Bus Route Roads & PWD', head: 'S. Rajendran', phone: '044-25384520' },
      { id: 'SWM', name: 'GCC Solid Waste Management', head: 'N. Mahesan', phone: '044-25384530' },
      { id: 'WATER', name: 'CMWSSB (Metro Water & Sewage)', head: 'R. Kanthimathi', phone: '044-45674567' },
      { id: 'LIGHT', name: 'GCC Electrical Department', head: 'K. Jaganathan', phone: '044-25384540' },
      { id: 'DISASTER', name: 'GCC 24x7 Control Room (1913)', head: 'M. S. Prashanth', phone: '1913' },
    ],
  },
};

// City-Specific Mock Complaints Dataset
export const CITY_COMPLAINTS = {
  mumbai: [
    {
      id: 'CP-MUM-2026-1042',
      category: 'POTHOLE',
      categoryLabel: 'Pothole & Road Damage',
      priority: 'CRITICAL',
      status: 'AWAITING_REVIEW',
      severity: 8.7,
      aiConfidence: 0.96,
      ward: 'Ward H-West (Bandra West)',
      location: 'Linking Road Traffic Junction',
      description: 'Deep 2ft pothole near traffic signal causing severe two-wheeler hazard after rain.',
      department: 'BMC Public Works Dept (Roads)',
      reportedAt: '2026-08-20 15:10',
      officer: 'Suresh Patil (BMC Crew #14)',
      lat: '19.0596° N',
      lng: '72.8295° E',
    },
    {
      id: 'CP-MUM-2026-1038',
      category: 'GARBAGE',
      categoryLabel: 'Solid Waste Overflow',
      priority: 'MEDIUM',
      status: 'ASSIGNED',
      severity: 5.2,
      aiConfidence: 0.91,
      ward: 'Ward A (Colaba / Fort)',
      location: 'Lane behind Sassoon Docks Market',
      description: 'Overflowing market waste bin blocking pedestrian walkway.',
      department: 'BMC Solid Waste Management',
      reportedAt: '2026-08-20 11:34',
      officer: 'Anjali Deshmukh (BMC SWM Team A)',
      lat: '18.9067° N',
      lng: '72.8147° E',
    },
    {
      id: 'CP-MUM-2026-1021',
      category: 'WATERLOGGING',
      categoryLabel: 'Drainage Waterlogging',
      priority: 'CRITICAL',
      status: 'IN_PROGRESS',
      severity: 9.1,
      aiConfidence: 0.94,
      ward: 'Ward G-South (Worli)',
      location: 'Worli Seaface Promenade Road',
      description: 'Stormwater drain blocked by silt causing water accumulation across 2 lanes.',
      department: 'BMC Stormwater Drainage Dept',
      reportedAt: '2026-08-20 09:15',
      officer: 'Vikram Shinde (BMC Hydraulic Crew)',
      lat: '19.0176° N',
      lng: '72.8172° E',
    },
    {
      id: 'CP-MUM-2026-1015',
      category: 'BROKEN_STREETLIGHT',
      categoryLabel: 'Streetlight Failure',
      priority: 'HIGH',
      status: 'RESOLVED',
      severity: 6.8,
      aiConfidence: 0.89,
      ward: 'Ward K-West (Andheri West)',
      location: 'Lokhandwala Complex Main Road',
      description: 'Four consecutive streetlights unlit near residential gates.',
      department: 'BEST & Electrical Cell',
      reportedAt: '2026-08-19 21:00',
      officer: 'Rajesh Kadam (BEST Crew)',
      lat: '19.1197° N',
      lng: '72.8464° E',
    }
  ],
  bengaluru: [
    {
      id: 'CP-BLR-2026-2091',
      category: 'BROKEN_STREETLIGHT',
      categoryLabel: 'BESCOM Streetlight Fault',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      severity: 7.1,
      aiConfidence: 0.88,
      ward: 'Indiranagar (Ward 80)',
      location: '100ft Road, 4th Cross',
      description: 'Entire stretch of 5 streetlights dark near Indiranagar Metro Station.',
      department: 'BESCOM & BBMP Electrical Cell',
      reportedAt: '2026-08-20 14:20',
      officer: 'K. Venkatesh (BESCOM Team #8)',
      lat: '12.9784° N',
      lng: '77.6408° E',
    },
    {
      id: 'CP-BLR-2026-2084',
      category: 'GARBAGE',
      categoryLabel: 'BBMP Garbage Dumping',
      priority: 'MEDIUM',
      status: 'AWAITING_REVIEW',
      severity: 5.8,
      aiConfidence: 0.93,
      ward: 'Koramangala (Ward 151)',
      location: '80ft Road, 5th Block Corner',
      description: 'Bulk commercial waste dumped overnight on public footpath.',
      department: 'BBMP Solid Waste Management',
      reportedAt: '2026-08-20 10:10',
      officer: 'Harish Kumar (BBMP SWM Zone 4)',
      lat: '12.9352° N',
      lng: '77.6245° E',
    },
    {
      id: 'CP-BLR-2026-2070',
      category: 'POTHOLE',
      categoryLabel: 'Whitefield Road Damage',
      priority: 'CRITICAL',
      status: 'ASSIGNED',
      severity: 8.9,
      aiConfidence: 0.95,
      ward: 'Whitefield (Ward 84)',
      location: 'ITPL Main Road Signal',
      description: 'Large crater in middle lane causing severe tech park traffic slowdowns.',
      department: 'BBMP Major Infrastructure & Roads',
      reportedAt: '2026-08-19 18:45',
      officer: 'B. S. Prahallad (BBMP Road Crew)',
      lat: '12.9698° N',
      lng: '77.7499° E',
    }
  ],
  delhi: [
    {
      id: 'CP-DEL-2026-3011',
      category: 'WATERLOGGING',
      categoryLabel: 'DJB Drain Waterlogging',
      priority: 'CRITICAL',
      status: 'AWAITING_REVIEW',
      severity: 9.1,
      aiConfidence: 0.94,
      ward: 'Connaught Place (NDMC)',
      location: 'Outer Circle, Radial Road 2',
      description: 'Deep waterlogging across 2 lanes following heavy rain near Rajiv Chowk.',
      department: 'Delhi Jal Board & NDMC PWD',
      reportedAt: '2026-08-20 13:00',
      officer: 'Anurag Srivastava (DJB Cell)',
      lat: '28.6315° N',
      lng: '77.2167° E',
    },
    {
      id: 'CP-DEL-2026-3005',
      category: 'POTHOLE',
      categoryLabel: 'MCD Road Pothole',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      severity: 7.6,
      aiConfidence: 0.90,
      ward: 'Rohini (Zone 7)',
      location: 'Sector 8 Main Market Road',
      description: 'Cave-in pothole near bus stop damaging vehicle axles.',
      department: 'MCD PWD Maintenance',
      reportedAt: '2026-08-20 08:30',
      officer: 'Rakesh Sharma (MCD Crew #12)',
      lat: '28.7041° N',
      lng: '77.1025° E',
    }
  ],
  pune: [
    {
      id: 'CP-PUN-2026-4055',
      category: 'FALLEN_TREE',
      categoryLabel: 'PMC Tree Branch Removal',
      priority: 'MEDIUM',
      status: 'RESOLVED',
      severity: 4.5,
      aiConfidence: 0.92,
      ward: 'Kothrud - Bavdhan',
      location: 'Ideal Colony Road',
      description: 'Fallen banyan tree branch cleared from residential access lane by PMC crew.',
      department: 'PMC Tree Authority & Gardens Dept',
      reportedAt: '2026-08-19 16:20',
      officer: 'Prashant Ranpise (PMC Crew)',
      lat: '18.5074° N',
      lng: '73.8077° E',
    },
    {
      id: 'CP-PUN-2026-4048',
      category: 'POTHOLE',
      categoryLabel: 'PMC Road Department Pothole',
      priority: 'HIGH',
      status: 'ASSIGNED',
      severity: 8.1,
      aiConfidence: 0.94,
      ward: 'Viman Nagar - Nagar Road',
      location: 'Near Datta Mandir Chowk',
      description: 'Deep road depression causing traffic bottleneck near airport road.',
      department: 'PMC Road Department',
      reportedAt: '2026-08-20 11:15',
      officer: 'Vikas Dhakane (PMC Road Crew)',
      lat: '18.5679° N',
      lng: '73.9143° E',
    }
  ],
  chennai: [
    {
      id: 'CP-CHE-2026-5012',
      category: 'GARBAGE',
      categoryLabel: 'GCC Sanitation Overflow',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      severity: 7.8,
      aiConfidence: 0.95,
      ward: 'T. Nagar (Zone 10)',
      location: 'Ranganathan Street Junction',
      description: 'Market waste collection bin overflowing onto shopping boulevard.',
      department: 'GCC Solid Waste Management',
      reportedAt: '2026-08-20 12:40',
      officer: 'N. Mahesan (GCC Zone 10 Crew)',
      lat: '13.0418° N',
      lng: '80.2341° E',
    },
    {
      id: 'CP-CHE-2026-5008',
      category: 'WATERLOGGING',
      categoryLabel: 'Metro Water Sewage Overflow',
      priority: 'CRITICAL',
      status: 'AWAITING_REVIEW',
      severity: 9.2,
      aiConfidence: 0.96,
      ward: 'Adyar (Zone 13)',
      location: 'LB Road Signal Crossing',
      description: 'Stormwater drain blockage causing water accumulation on bus route.',
      department: 'CMWSSB Metro Water & Sewage',
      reportedAt: '2026-08-20 07:50',
      officer: 'R. Kanthimathi (CMWSSB Team)',
      lat: '13.0012° N',
      lng: '80.2565° E',
    }
  ]
};

// City-Specific Analytics Profiles
export const CITY_ANALYTICS = {
  mumbai: {
    totalComplaints: 482,
    openComplaints: 38,
    resolvedComplaints: 444,
    slaCompliance: '96.4%',
    avgResolutionHours: 12.8,
    dailyVolume: [
      { day: 'Mon', count: 64, resolved: 58 },
      { day: 'Tue', count: 72, resolved: 69 },
      { day: 'Wed', count: 85, resolved: 81 },
      { day: 'Thu', count: 59, resolved: 55 },
      { day: 'Fri', count: 91, resolved: 88 },
      { day: 'Sat', count: 48, resolved: 46 },
      { day: 'Sun', count: 63, resolved: 60 },
    ],
    categories: [
      { name: 'Potholes (BMC PWD)', count: 184, percentage: 38, icon: '🛣️' },
      { name: 'Solid Waste (BMC SWM)', count: 142, percentage: 29, icon: '🗑️' },
      { name: 'Waterlogging (BMC Drainage)', count: 86, percentage: 18, icon: '💧' },
      { name: 'Streetlights (BEST Electrical)', count: 52, percentage: 11, icon: '💡' },
      { name: 'Fallen Trees (BMC Greenery)', count: 18, percentage: 4, icon: '🌳' },
    ]
  },
  bengaluru: {
    totalComplaints: 395,
    openComplaints: 29,
    resolvedComplaints: 366,
    slaCompliance: '95.1%',
    avgResolutionHours: 14.2,
    dailyVolume: [
      { day: 'Mon', count: 52, resolved: 48 },
      { day: 'Tue', count: 61, resolved: 57 },
      { day: 'Wed', count: 74, resolved: 70 },
      { day: 'Thu', count: 48, resolved: 45 },
      { day: 'Fri', count: 80, resolved: 76 },
      { day: 'Sat', count: 39, resolved: 37 },
      { day: 'Sun', count: 41, resolved: 39 },
    ],
    categories: [
      { name: 'BESCOM Streetlights', count: 148, percentage: 37, icon: '💡' },
      { name: 'BBMP Garbage Dumping', count: 118, percentage: 30, icon: '🗑️' },
      { name: 'Potholes (BBMP Infra)', count: 82, percentage: 21, icon: '🛣️' },
      { name: 'BWSSB Water Leaks', count: 47, percentage: 12, icon: '💧' },
    ]
  },
  delhi: {
    totalComplaints: 520,
    openComplaints: 46,
    resolvedComplaints: 474,
    slaCompliance: '94.8%',
    avgResolutionHours: 15.5,
    dailyVolume: [
      { day: 'Mon', count: 75, resolved: 70 },
      { day: 'Tue', count: 82, resolved: 78 },
      { day: 'Wed', count: 96, resolved: 90 },
      { day: 'Thu', count: 68, resolved: 63 },
      { day: 'Fri', count: 104, resolved: 98 },
      { day: 'Sat', count: 51, resolved: 47 },
      { day: 'Sun', count: 44, resolved: 41 },
    ],
    categories: [
      { name: 'MCD PWD Potholes', count: 210, percentage: 40, icon: '🛣️' },
      { name: 'MCD Sanitation', count: 165, percentage: 32, icon: '🗑️' },
      { name: 'Delhi Jal Board Water', count: 95, percentage: 18, icon: '💧' },
      { name: 'BSES Streetlights', count: 50, percentage: 10, icon: '💡' },
    ]
  },
  pune: {
    totalComplaints: 280,
    openComplaints: 18,
    resolvedComplaints: 262,
    slaCompliance: '97.5%',
    avgResolutionHours: 10.4,
    dailyVolume: [
      { day: 'Mon', count: 38, resolved: 36 },
      { day: 'Tue', count: 42, resolved: 40 },
      { day: 'Wed', count: 49, resolved: 47 },
      { day: 'Thu', count: 35, resolved: 34 },
      { day: 'Fri', count: 55, resolved: 52 },
      { day: 'Sat', count: 31, resolved: 29 },
      { day: 'Sun', count: 30, resolved: 28 },
    ],
    categories: [
      { name: 'PMC Road Dept Potholes', count: 110, percentage: 39, icon: '🛣️' },
      { name: 'PMC Sanitation SWM', count: 85, percentage: 30, icon: '🗑️' },
      { name: 'PMC Water Supply', count: 55, percentage: 20, icon: '💧' },
      { name: 'PMC Tree Removal', count: 30, percentage: 11, icon: '🌳' },
    ]
  },
  chennai: {
    totalComplaints: 340,
    openComplaints: 24,
    resolvedComplaints: 316,
    slaCompliance: '96.0%',
    avgResolutionHours: 11.9,
    dailyVolume: [
      { day: 'Mon', count: 46, resolved: 43 },
      { day: 'Tue', count: 52, resolved: 49 },
      { day: 'Wed', count: 61, resolved: 58 },
      { day: 'Thu', count: 42, resolved: 40 },
      { day: 'Fri', count: 68, resolved: 64 },
      { day: 'Sat', count: 38, resolved: 35 },
      { day: 'Sun', count: 33, resolved: 31 },
    ],
    categories: [
      { name: 'GCC Solid Waste SWM', count: 125, percentage: 37, icon: '🗑️' },
      { name: 'CMWSSB Sewage & Water', count: 105, percentage: 31, icon: '💧' },
      { name: 'GCC Bus Route Roads', count: 75, percentage: 22, icon: '🛣️' },
      { name: 'GCC Streetlighting', count: 35, percentage: 10, icon: '💡' },
    ]
  }
};

export function getCityData(cityId) {
  return INDIA_CITIES[cityId] || INDIA_CITIES.mumbai;
}

export function getCityComplaints(cityId) {
  return CITY_COMPLAINTS[cityId] || CITY_COMPLAINTS.mumbai;
}

export function getCityAnalytics(cityId) {
  return CITY_ANALYTICS[cityId] || CITY_ANALYTICS.mumbai;
}
